VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "devops-vm"
  config.vm.network :private_network, ip: "192.168.58.111"

  config.vm.synced_folder "data", "/vagrant_data"
  config.vm.synced_folder "scripts", "/vagrant_scripts"


  config.vm.provider :virtualbox do |vb|
   
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '8192',
      '--cpus', '2'
    ]
    
  end  
  config.vm.provision "file", source: "~/.ssh/id_rsa_devops_course.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys"
  
  config.vm.provision "shell", inline: <<-SHELL
     	sudo apt-get update
     	sudo apt-get install dpkg     	
   	SHELL
   
  
  
end
