# -*- mode: ruby -*-
#
# vi: set ft=ruby :
# vim: ts=2

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "registry-vm"
  config.vm.box_download_insecure = false 
  
  ENV['LC_ALL']="en_US.UTF-8"
  
  #config.vm.network "forwarded_port", guest: 5001, host: 8081, host_ip: "192.168.33.8"
  #config.vm.network "forwarded_port", guest: 443, host: 8088, host_ip: "192.168.33.8"
  
  #config.vm.network "forwarded_port", guest: 5001, host: 8081
  #config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.network :private_network, ip: "192.168.33.8"

  config.vm.synced_folder "../../data", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
   
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '8192',
      '--cpus', '2'
    ]
    
  end  
  
  config.vm.provision "shell", inline: <<-SHELL
     	sudo apt-get update
     	sudo apt-get install --yes python
     	sudo apt-get install -y apache2

   	SHELL
   
  config.vm.provision "ansible" do |ansible|
    	ansible.playbook = "./playbook/playbook.yml"
  end
  
end